development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: thanks-bank_development
  pool: 5
  username: railsuser
  password: railspass
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: thanks-bank_test
  pool: 5
  username: railsuser
  password: railspass
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: thanks-bank_production
  pool: 5
  username: railsuser
  password: railspass
  host: localhost
